"""
InstaBio EPUB Export Module (R3.3)
Generates EPUB e-books from biography chapters.

Falls back to basic HTML file if ebooklib is unavailable.
"""

import logging
import os
from datetime import datetime, UTC
from typing import Optional, List, Dict

logger = logging.getLogger(__name__)

# Check for ebooklib availability
_HAS_EBOOKLIB = False
try:
    from ebooklib import epub
    _HAS_EBOOKLIB = True
except ImportError:
    logger.warning("ebooklib not installed — EPUB export will use basic HTML fallback")


def generate_biography_epub(
    chapters: List[Dict],
    user_name: str,
    birth_year: Optional[int] = None,
) -> bytes:
    """
    Generate an EPUB e-book from biography chapters.
    
    Args:
        chapters: List of chapter dicts with 'title', 'body'
        user_name: Author's name
        birth_year: Optional birth year
    
    Returns:
        EPUB bytes
    """
    if _HAS_EBOOKLIB:
        return _build_epub(chapters, user_name, birth_year)
    else:
        return _build_fallback_html(chapters, user_name, birth_year)


def _build_epub(chapters, user_name, birth_year):
    """Build EPUB using ebooklib."""
    book = epub.EpubBook()
    
    # Metadata
    book.set_identifier(f'instabio-{user_name.lower().replace(" ", "-")}-{datetime.now(UTC).strftime("%Y%m%d")}')
    book.set_title(f'{user_name} — A Life Story')
    book.set_language('en')
    book.add_author(user_name)
    book.add_metadata('DC', 'publisher', 'InstaBio — instabio.ai')
    book.add_metadata('DC', 'date', datetime.now(UTC).strftime('%Y-%m-%d'))
    
    # CSS
    style = epub.EpubItem(
        uid='style',
        file_name='style/default.css',
        media_type='text/css',
        content=b"""
body { font-family: Georgia, serif; line-height: 1.8; color: #2A2A2A; margin: 1em; }
h1 { font-size: 2em; color: #2D5016; text-align: center; margin-bottom: 0.5em; }
h2 { font-size: 1.5em; color: #2D5016; border-bottom: 2px solid #2D5016; padding-bottom: 4px; margin-top: 2em; }
p { text-indent: 1.5em; margin-bottom: 0.8em; }
.cover { text-align: center; padding-top: 30%; }
.cover .subtitle { color: #666; font-size: 1.2em; }
.footer { text-align: center; font-size: 0.8em; color: #999; margin-top: 3em; }
"""
    )
    book.add_item(style)
    
    # Cover chapter
    cover_html = f"""<html><body>
    <div class="cover">
        <h1>{_escape(user_name)}</h1>
        <p class="subtitle">A Life Story</p>
        {f'<p class="subtitle">Born {birth_year}</p>' if birth_year else ''}
        <p style="margin-top:3em; font-size:0.8em; color:#999;">Generated by InstaBio</p>
    </div>
    </body></html>"""
    
    cover_ch = epub.EpubHtml(title='Cover', file_name='cover.xhtml', lang='en')
    cover_ch.content = cover_html.encode('utf-8')
    cover_ch.add_item(style)
    book.add_item(cover_ch)
    
    # Content chapters
    epub_chapters = [cover_ch]
    toc = []
    
    for i, ch in enumerate(chapters, 1):
        title = ch.get('title', f'Chapter {i}')
        body = ch.get('body', '')
        
        paragraphs = body.split('\n\n') if body else [body]
        body_html = '\n'.join(f'<p>{_escape(p.strip())}</p>' for p in paragraphs if p.strip())
        
        chapter_html = f"""<html><body>
        <h2>Chapter {i}: {_escape(title)}</h2>
        {body_html}
        </body></html>"""
        
        epub_ch = epub.EpubHtml(
            title=f'Chapter {i}: {title}',
            file_name=f'chapter_{i}.xhtml',
            lang='en'
        )
        epub_ch.content = chapter_html.encode('utf-8')
        epub_ch.add_item(style)
        book.add_item(epub_ch)
        epub_chapters.append(epub_ch)
        toc.append(epub_ch)
    
    # Table of contents
    book.toc = toc
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    
    # Spine
    book.spine = ['nav'] + epub_chapters
    
    # Write to bytes
    import io
    output = io.BytesIO()
    epub.write_epub(output, book)
    return output.getvalue()


def _build_fallback_html(chapters, user_name, birth_year):
    """Fallback: return HTML bytes when ebooklib not available."""
    chapters_html = ""
    for i, ch in enumerate(chapters, 1):
        title = ch.get('title', f'Chapter {i}')
        body = ch.get('body', '')
        paragraphs = body.split('\n\n') if body else [body]
        body_html = '\n'.join(f'<p>{_escape(p.strip())}</p>' for p in paragraphs if p.strip())
        chapters_html += f'<h2>Chapter {i}: {_escape(title)}</h2>\n{body_html}\n'
    
    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{_escape(user_name)} — A Life Story</title>
<style>body {{ font-family: Georgia, serif; max-width: 700px; margin: 2em auto; line-height: 1.8; }}
h1 {{ color: #2D5016; text-align: center; }} h2 {{ color: #2D5016; }}</style></head>
<body>
<h1>{_escape(user_name)}</h1>
<p style="text-align:center; color:#666;">A Life Story{f' · Born {birth_year}' if birth_year else ''}</p>
{chapters_html}
<p style="text-align:center; color:#999; margin-top:3em;">Generated by InstaBio</p>
</body></html>"""
    return html.encode('utf-8')


def _escape(text: str) -> str:
    """Escape HTML special characters."""
    if not text:
        return ""
    return (text
        .replace('&', '&amp;')
        .replace('<', '&lt;')
        .replace('>', '&gt;')
        .replace('"', '&quot;'))
