"""
InstaBio PDF Export Module (R3.2/R3.8)
Generates professional PDF biographies with cover page, table of contents,
chapters, confidence footnotes, and print-ready formatting.

Falls back to basic HTML-to-PDF if weasyprint is unavailable.
"""

import json
import logging
import os
import re
import tempfile
from datetime import datetime, UTC
from pathlib import Path
from typing import Optional, List, Dict

logger = logging.getLogger(__name__)

# Check for weasyprint availability
_HAS_WEASYPRINT = False
try:
    import weasyprint
    _HAS_WEASYPRINT = True
except ImportError:
    logger.warning("weasyprint not installed — PDF export will use basic HTML rendering")


def generate_biography_pdf(
    chapters: List[Dict],
    user_name: str,
    birth_year: Optional[int] = None,
    photo_path: Optional[str] = None,
    format_type: str = "standard",  # "standard" or "print"
) -> bytes:
    """
    Generate a professional PDF from biography chapters.
    
    Args:
        chapters: List of chapter dicts with 'title', 'body', 'confidence', 'citations'
        user_name: Author's name for cover page
        birth_year: Optional birth year for subtitle
        photo_path: Optional path to author photo for cover
        format_type: "standard" for screen, "print" for 6x9 book format
    
    Returns:
        PDF bytes
    """
    html = _build_biography_html(chapters, user_name, birth_year, photo_path, format_type)
    
    if _HAS_WEASYPRINT:
        return _render_with_weasyprint(html)
    else:
        return _render_basic_pdf(html)


def generate_journal_pdf(
    entries: List[Dict],
    user_name: str,
) -> bytes:
    """Generate a PDF journal/diary from journal entries."""
    html = _build_journal_html(entries, user_name)
    
    if _HAS_WEASYPRINT:
        return _render_with_weasyprint(html)
    else:
        return _render_basic_pdf(html)


def _build_biography_html(chapters, user_name, birth_year, photo_path, format_type):
    """Build HTML for the biography PDF."""
    page_size = "6in 9in" if format_type == "print" else "A4"
    margin = "1in 0.75in" if format_type == "print" else "0.75in"
    
    cover_subtitle = ""
    if birth_year:
        cover_subtitle = f"<p class='subtitle'>Born {birth_year}</p>"
    
    photo_html = ""
    if photo_path and os.path.exists(photo_path):
        photo_html = f'<img src="file://{photo_path}" class="cover-photo" />'
    
    # Build TOC
    toc_items = ""
    for i, ch in enumerate(chapters, 1):
        title = ch.get('title', f'Chapter {i}')
        toc_items += f'<li><span class="toc-title">{_escape(title)}</span></li>\n'
    
    # Build chapters
    chapter_html = ""
    for i, ch in enumerate(chapters, 1):
        title = ch.get('title', f'Chapter {i}')
        body = ch.get('body', '')
        confidence = ch.get('confidence', 'high')
        
        # Parse paragraphs
        paragraphs = body.split('\n\n') if body else [body]
        body_html = ""
        for p in paragraphs:
            p = p.strip()
            if p:
                conf_icon = _confidence_icon(confidence)
                body_html += f'<p>{conf_icon} {_escape(p)}</p>\n'
        
        chapter_html += f"""
        <div class="chapter">
            <h2>Chapter {i}: {_escape(title)}</h2>
            {body_html}
        </div>
        """
    
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
@page {{ size: {page_size}; margin: {margin}; }}
body {{ font-family: Georgia, 'Times New Roman', serif; font-size: 12pt; line-height: 1.8; color: #2A2A2A; }}
.cover {{ text-align: center; page-break-after: always; padding-top: 3in; }}
.cover h1 {{ font-size: 28pt; color: #2D5016; margin-bottom: 12px; }}
.cover .subtitle {{ font-size: 16pt; color: #666; }}
.cover .author {{ font-size: 18pt; color: #333; margin-top: 24px; }}
.cover-photo {{ max-width: 200px; max-height: 200px; border-radius: 50%; margin-bottom: 24px; }}
.toc {{ page-break-after: always; }}
.toc h2 {{ font-size: 20pt; color: #2D5016; margin-bottom: 24px; }}
.toc ol {{ font-size: 14pt; line-height: 2; }}
.toc-title {{ color: #333; }}
.chapter {{ page-break-before: always; }}
.chapter h2 {{ font-size: 20pt; color: #2D5016; border-bottom: 2px solid #2D5016; padding-bottom: 8px; margin-bottom: 24px; }}
.chapter p {{ margin-bottom: 16px; text-indent: 0.3in; }}
.conf-icon {{ font-size: 10pt; opacity: 0.5; }}
.footer {{ text-align: center; font-size: 10pt; color: #999; margin-top: 48px; border-top: 1px solid #ddd; padding-top: 12px; }}
</style>
</head>
<body>
    <div class="cover">
        {photo_html}
        <h1>{_escape(user_name)}</h1>
        <p class="author">A Life Story</p>
        {cover_subtitle}
        <p style="margin-top:48px; font-size:10pt; color:#999;">Generated by InstaBio — instabio.ai</p>
    </div>
    
    <div class="toc">
        <h2>Table of Contents</h2>
        <ol>{toc_items}</ol>
    </div>
    
    {chapter_html}
    
    <div class="footer">
        Generated by InstaBio · {datetime.now(UTC).strftime('%B %d, %Y')} · instabio.ai
    </div>
</body>
</html>"""


def _build_journal_html(entries, user_name):
    """Build HTML for journal PDF."""
    entries_html = ""
    for entry in entries:
        date = entry.get('date', 'Unknown date')
        title = entry.get('title', '')
        body = entry.get('body', '')
        mood = entry.get('mood', '')
        
        entries_html += f"""
        <div class="entry">
            <h3>{_escape(date)} {f'— {_escape(title)}' if title else ''}</h3>
            {f'<div class="mood">{_escape(mood)}</div>' if mood else ''}
            <p>{_escape(body)}</p>
        </div>
        """
    
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
@page {{ size: A4; margin: 0.75in; }}
body {{ font-family: Georgia, serif; font-size: 12pt; line-height: 1.8; color: #2A2A2A; }}
.cover {{ text-align: center; page-break-after: always; padding-top: 3in; }}
.cover h1 {{ font-size: 24pt; color: #2D5016; }}
.entry {{ margin-bottom: 32px; padding-bottom: 16px; border-bottom: 1px solid #eee; }}
.entry h3 {{ font-size: 14pt; color: #2D5016; margin-bottom: 8px; }}
.entry p {{ text-indent: 0.3in; }}
.mood {{ font-style: italic; color: #666; margin-bottom: 8px; }}
</style>
</head>
<body>
    <div class="cover">
        <h1>The Journal of {_escape(user_name)}</h1>
        <p style="color:#666; margin-top:12px;">Generated by InstaBio</p>
    </div>
    {entries_html}
</body>
</html>"""


def _render_with_weasyprint(html: str) -> bytes:
    """Render HTML to PDF using weasyprint."""
    doc = weasyprint.HTML(string=html)
    return doc.write_pdf()


def _render_basic_pdf(html: str) -> bytes:
    """Fallback: return HTML bytes wrapped as a simple document."""
    # Without weasyprint, return the HTML as downloadable content
    # The client can print-to-PDF from their browser
    return html.encode('utf-8')


def _escape(text: str) -> str:
    """Escape HTML special characters."""
    if not text:
        return ""
    return (text
        .replace('&', '&amp;')
        .replace('<', '&lt;')
        .replace('>', '&gt;')
        .replace('"', '&quot;'))


def _confidence_icon(level: str) -> str:
    """Return HTML confidence icon."""
    icons = {
        'exact': '<span class="conf-icon">📌</span>',
        'approximate': '<span class="conf-icon">~</span>',
        'inferred': '<span class="conf-icon">❓</span>',
    }
    return icons.get(level, '')
